package com.controller;


import java.io.IOException;


import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.dao.PatientDao;
import com.model.Patient;
import com.util.Encryption;
import com.util.Generator;




@WebServlet("/admin")
public class AdminController extends HttpServlet {

	/**
	 * Autogenerated identifier used for <b>serialization</b> and <b>deserialization</b>.
	 */
	private static final long serialVersionUID = -3181915305413793528L;
	private PatientDao dao;
	private Generator gen;
	

	public AdminController() {
		super();
		dao = new PatientDao();
		gen = new Generator();
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		String forward="";
		String action = request.getParameter("action");
		response.setContentType("text/html; charset=UTF-8");
		response.setCharacterEncoding("UTF-8");
		request.setCharacterEncoding("UTF-8");
		
		HttpSession session = request.getSession(false);
		
		//check if session exists
		if(session == null) {
			forward = "/falseRequest.jsp";
		}
		//check if session Attribute exists
		else if(session.getAttribute("role") == null) {
			forward = "/falseRequest.jsp";
		}
		//check if the user is a doctor
		else if(!(session.getAttribute("role").equals("admin"))) {
			forward = "/falseRequest.jsp";
		}
		else {
			if(action.equalsIgnoreCase("appointments")) {
				forward = "/admin/appointments.jsp";
			}
			else if(action.equalsIgnoreCase("welcome")) {
				forward = "/admin/welcomeadmin.jsp";
			}
			else if(action.equalsIgnoreCase("details")) {
				forward = "/admin/admindetails.jsp";
			}
			else if(action.equalsIgnoreCase("addpatient")) {
				forward = "/admin/addpatient.jsp";
				request.setAttribute("message", "nomessage");
			}
			else if(action.equalsIgnoreCase("adddoctor")) {
				forward = "/admin/adddoctor.jsp";
			}
		}
		
		RequestDispatcher view = request.getRequestDispatcher(forward);
		view.forward(request, response);
	}
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		String forward = "";
		String action = request.getParameter("action");
		response.setContentType("text/html; charset=UTF-8");
		response.setCharacterEncoding("UTF-8");
		request.setCharacterEncoding("UTF-8");
		
		
		
		
		if(action.equalsIgnoreCase("insertpatient")) {
			
			forward = "/admin/addpatient.jsp";
			
			
			Patient p = new Patient();
			
			//get data from the request
			String name = request.getParameter("name");
			String surName = request.getParameter("surname");
			String amka = request.getParameter("amka");
			String username = request.getParameter("username");
			String password = request.getParameter("psw");

			
			//check data
			if(true) {
				//pass data to object
				p.setName(name);
				p.setSurname(surName);
				p.setSalt(gen.generate(16));
				p.setPassword(Encryption.getHashMD5(password, p.getSalt()));
				p.setUsername(username);
				p.setAMKA(amka);
				
				//call dao
				int check = dao.addPatient(p);
				
				if(check == 1) {
					request.setAttribute("message", "Success");
				}
					
				else {
					request.setAttribute("message", "Fail");
				}
			
			
			}
			
			
		}
		else if(action.equalsIgnoreCase("insertdoctor")) {
			
		}
		
		
		
		RequestDispatcher view = request.getRequestDispatcher(forward);
		view.forward(request, response);
	}
	
	
}
